[project] 
name = "Base"
description = "Base Repo"
version = "v1"
company = "Oguzhan"
author = "Mert OGUZHAN" 

[logger]
filepath="./logs/base.log"
rotation="50MB"

[connection]
    database_type= "postgresql"
    db_username= "postgres"
    db_password= "admin"
    db_host= "localhost"
    db_port= "5432"
    db_name= "workplace"

[crud]
    database_type= "postgresql"
    db_username= "postgres"
    db_password= "admin"
    db_host= "localhost"
    db_port= "5432"
    db_name= "workplace"

[fastapi]
database_type= "postgresql"
host= "0.0.0.0"
port= 8000
reload= "true"
log_level= "info"
chatbot_model_name = "gemini-2.5-flash"
temperature_for_chatbot = 0.2
summarizer_model_name = "gemini-2.5-flash"
retrieved_chunk_threshold_for_agent_quiz = 0.7

[LabelExtractor]
model_name = "gemini-2.5-flash" # gemini-2.0-flash", gemini-pro
temperature = 0.2 # temperature düşürdüğümde (0'a yaklaştığımda) daha deterministik (kesin, en olası) cevabı verir.
max_retries = 2

[JsonHandler]
directory = "/home/mert/projects/btk/app/data"

[RagPipeline]
model_name= "models/gemini-embedding-exp-03-07"
vector_db_directory= "vector_db"